plugins {
    id 'com.android.application'
}

android {
    namespace 'com.liverussia.trucker'
    compileSdk 33

    defaultConfig {
        applicationId "com.liverussia.trucker"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
    }
}
